Repository vishnu2k60/MyIdentityCard-v2, pull requests merged in 2022-10, with the labels that each got.

#1 Update index.html
  index.html
Labels: hacktoberfest-accepted

#2 Update index.html
  index.html
Labels: invalid, hacktoberfest-accepted

#3 Add files via upload
  stringsubset.cpp
Labels: hacktoberfest-accepted

#4 Add files via upload
  intro recursion.cpp
Labels: hacktoberfest-accepted

#5 Add files via upload
  subsequences.cpp
Labels: hacktoberfest-accepted

#6 Update index.html
  index.html
Labels: hacktoberfest-accepted, spam

#7 Update index.html
  index.html
Labels: hacktoberfest-accepted

#8 Update index.html
  index.html
Labels: hacktoberfest-accepted

#9 Update index.html
  index.html
Labels: hacktoberfest-accepted

#10 Update index.html
  index.html
Labels: hacktoberfest-accepted

#11 Update index.html
  index.html
Labels: hacktoberfest-accepted

#12 Update index.html
  index.html
Labels: hacktoberfest-accepted

#13 Update index.html
  index.html
Labels: hacktoberfest-accepted

#14 Update index.html
  index.html
Labels: hacktoberfest-accepted

#15 Update index.html
  index.html
Labels: hacktoberfest-accepted

#16 Update index.html
  index.html
Labels: hacktoberfest-accepted
